[project]
authors = ["atrawog <atrawog@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "jupyter"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
jupyterserver = "jupyter-server --config $JS_CONFIG"
jupyterhub = "jupyterhub --config $JH_CONFIG"
mcpo = "mcpo --port $MCPO_PORT -c $MCPO_CONFIG"
mcp-server-time = "mcp-proxy --host 0.0.0.0 --port $MCP_SERVER_TIME_PORT --pass-environment -- mcp-server-time"
mcp-server-fetch = "mcp-proxy --host 0.0.0.0 --port $MCP_SERVER_FETCH_PORT --pass-environment -- mcp-server-fetch --ignore-robots-txt --user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36'"
mcp-brave-search = "mcp-proxy  --host 0.0.0.0 --port $MCP_BRAVE_SEARCH_PORT --pass-environment -- npx -y @modelcontextprotocol/server-brave-search"
mcp-notebook="cursor-notebook-mcp --transport sse --allow-root $MCP_NOTEBOOK_DIR --host 0.0.0.0 --port $MCP_NOTEBOOK_PORT"

[dependencies]
python = "3.11.*"

[pypi-dependencies]
jupyterhub = ">=5.2.1, <6"
jupyter-ai = ">=2.29.1, <3"
jupyterlab = ">=4.3.5, <5"
mystmd = ">=1.3.23, <2"
jupyter-ai-magics = ">=2.29.1, <3"
jupyter-book = "==2.0.0a1"
jupyterlab-myst = ">=2.4.2, <3"
langchain-ollama = ">=0.2.3, <0.3"
ansible = ">=11.2.0, <12"
ansible-runner = ">=2.4.0, <3"
libvirt-python = ">=11.0.0, <12"
altair = ">=5.5.0, <6"
numpy = ">=1.26.4, <2"
pandas = ">=2.2.3, <3"
geopandas = ">=1.0.1, <2"
kubernetes = ">=32.0.1, <33"
nbdev = ">=2.3.34, <3"
papermill = ">=2.6.0, <3"
fastapi = ">=0.115.12, <0.116"
configurable-http-proxy = ">=0.3.0, <0.4"
triton = ">=3.1.0, <4"
cut-cross-entropy = ">=25.1.1, <26"
unsloth-zoo = ">=2025.2.5, <2026"
protobuf = ">=3.20.3, <4"
datasets = ">=3.5.0, <4"
hf-transfer = ">=0.1.9, <0.2"
tqdm = ">=4.67.1, <5"
ipywidgets = ">=8.1.5, <9"
trl = ">=0.15.2, <0.16"
pip = ">=25.0.1, <26"
openai = ">=1.63.2, <2"
langchain-openai = ">=0.3.14, <0.4"
langchain-aws = ">=0.2.13, <0.3"
langchain-anthropic = ">=0.3.7, <0.4"
langchain-cohere = ">=0.4.2, <0.5"
langchain-google-genai = ">=2.0.9, <3"
langchain-mistralai = ">=0.2.6, <0.3"
langchain-nvidia-ai-endpoints = ">=0.3.9, <0.4"
folium = ">=0.19.4, <0.20"
matplotlib = ">=3.10.1, <4"
mapclassify = ">=2.8.1, <3"
together = ">=1.3.14, <2"
umap-learn = { version = ">=0.5.7, <0.6", extras = ["plot"] }
graphviz = ">=0.20.3, <0.21"
orjson = ">=3.10.15, <4"
dataset = ">=1.6.2, <2"
wandb = ">=0.19.10, <0.20"
python-levenshtein = ">=0.26.1, <0.27"
byaldi = ">=0.0.5, <0.0.6"
pdf2image = ">=1.17.0, <2"
duckduckgo-search = ">=7.4.3, <8"
tiktoken = ">=0.9.0, <0.10"
beautifulsoup4 = ">=4.13.4, <5"
bm25s = ">=0.2.7.post1, <0.3"
ffmpeg-python = ">=0.2.0, <0.3"
pyaudio = ">=0.2.14, <0.3"
pypdf = ">=5.4.0, <6"
cartesia = ">=1.4.0, <2"
bert-score = ">=0.3.13, <0.4"
rouge-score = ">=0.1.2, <0.2"
evaluate = ">=0.4.3, <0.5"
seaborn = ">=0.13.2, <0.14"
osmium = ">=4.0.2, <5"
osmnx = ">=2.0.1, <3"
rasterio = ">=1.4.3, <2"
gdal = "==3.10.1"
h3 = ">=4.2.1, <5"
ipyleaflet = ">=0.19.2, <0.20"
pyrosm = ">=0.6.2, <0.7"
pydriosm = ">=2.2.0, <3"
r5py = { git = "git+https://github.com/r5py/r5py.git" }
routingpy = ">=1.3.0, <2"
polyline = ">=2.0.2, <3"
boto3 = ">=1.37.19, <2"
mcp = ">=1.6.0, <2"
mcpo = ""
mcp-server-time = ">=0.6.2, <0.7"
mcp-server-fetch = ">=2025.4.7, <2026"
apache-airflow = ">=2.10.3, <3"
comfy-cli = ">=1.3.8, <2"
sparqlwrapper = ">=2.0.0, <3"
requests = ">=2.32.3, <3"
selenium = ">=4.31.0, <5"
playwright = ">=1.51.0, <2"
scrapy = ">=2.12.0, <3"
lxml = ">=5.4.0, <6"
requests-html = ">=0.10.0, <0.11"
aiohttp = ">=3.11.18, <4"
newspaper3k = ">=0.2.8, <0.3"
pyquery = ">=2.0.1, <3"
parsel = ">=1.10.0, <2"
langchain = ">=0.3.24, <0.4"
langchain-community = ">=0.3.23, <0.4"
chromadb = ">=0.6.3, <0.7"
sentence-transformers = ">=4.1.0, <5"
python-dotenv = ">=1.1.0, <2"
pytesseract = ">=0.3.13, <0.4"
easyocr = ">=1.7.2, <2"
pypdf2 = ">=3.0.1, <4"
pillow = ">=10.4.0, <11"
faiss-cpu = ">=1.11.0, <2"
unstructured = ">=0.17.2, <0.18"
opencv-python = ">=4.11.0.86, <5"
gradio = ">=5.27.0, <6"
pydantic = ">=2.11.4, <3"
uvicorn = ">=0.34.2, <0.35"
nest-asyncio = ">=1.6.0, <2"
langchain-core = ">=0.3.56, <0.4"
langchain-chroma = ">=0.2.3, <0.3"
langchain-text-splitters = ">=0.3.8, <0.4"
httpx = "*"
python-multipart = ">=0.0.20, <0.0.21"
aiofiles = ">=24.1.0, <25"
plotly = ">=6.0.1, <7"
scikit-learn = ">=1.6.1, <2"
spacy = "*"
nltk = ">=3.9.1, <4"
redis = ">=5.2.1, <6"
qdrant-client = ">=1.14.2, <2"
weaviate-client = ">=3.26.7, <4"
pinecone-client = ">=6.0.0, <7"
docx2txt = ">=0.9, <0.10"
llama-index = ">=0.12.33, <0.13"
streamlit = ">=1.45.0, <2"
torch = {version = "*", index = "https://download.pytorch.org/whl/cu128"}
torchvision = {version = "*", index = "https://download.pytorch.org/whl/cu128"}
torchaudio = {version = "*", index = "https://download.pytorch.org/whl/cu128"}
bitsandbytes = ">=0.41.1"
transformers = ">=4.36.0"
unsloth = ">=0.3.0"
accelerate = ">=0.23.0"
peft = "*"
huggingface_hub = ">=0.17.0"
packaging = "*"
ollama = "*"
mcp-proxy = ">=0.6.0, <0.7"
cursor-notebook-mcp = { version = ">=0.2.3, <0.3", extras = ["sse"] }
