[project]
authors = ["atrawog <atrawog@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "openwebui"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
openwebui = "DATA_DIR=$OW_DATA_DIR open-webui serve --port $OW_PORT"

[dependencies]
python = "3.11.*"
pip = ">=25.0.1,<26"

[pypi-dependencies]
open-webui = ">=0.6, <0.7"
mcpo = ">=0.0.1, <0.0.2"
mcp = { version = ">=1.6.0, <2", extras = ["cli"] }
