- name: Get k3s kubeconfig
  hosts: server
  tasks:
    - name: Fetch kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/k3s-config
        flat: yes
      become: yes

    - name: Ensure ~/.kube directory exists
      delegate_to: localhost
      file:
        path: ~/.kube
        state: directory
        mode: '0700'

    - name: Deploy kubeconfig locally
      delegate_to: localhost
      copy:
        src: /tmp/k3s-config
        dest: ~/.kube/config
        remote_src: yes

    - name: Update kubeconfig endpoint
      delegate_to: localhost
      replace:
        path: ~/.kube/config
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://{{ hostvars[inventory_hostname].ansible_host }}:6443'
