[project]
authors = ["atrawog <atrawog@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "jupyter"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
jupyterserver = "jupyter-server --config $JS_CONFIG"
jupyterhub = "jupyterhub --config $JH_CONFIG"

[dependencies]
python = "3.11.*"

[pypi-dependencies]
unsloth = { git = "git+https://github.com/unslothai/unsloth.git", extras = ["colab-new"] }
peft = ">=0.11.1, <0.12"
accelerate = ">=1.4.0, <2"
bitsandbytes = ">=0.45.2, <0.46"
torch = ">=2.5.1, <3"
torchvision = ">=0.20.1, <0.21"
torchaudio = ">=2.5.1, <3"
transformers = ">=4.49.0, <5"
mistral = ">=19.0.0, <20"
mistral-inference = ">=1.5.0, <2"
jupyterhub = ">=5.2.1, <6"
jupyter-ai = ">=2.29.1, <3"
jupyterlab = ">=4.3.5, <5"
mystmd = ">=1.3.23, <2"
jupyter-ai-magics = ">=2.29.1, <3"
jupyter-book = "==2.0.0a1"
jupyterlab-myst = ">=2.4.2, <3"
langchain-ollama = ">=0.2.3, <0.3"
ansible = ">=11.2.0, <12"
ansible-runner = ">=2.4.0, <3"
libvirt-python = ">=11.0.0, <12"
huggingface-hub = ">=0.29.0, <0.30"
altair = ">=5.5.0, <6"
numpy = ">=1.26.4, <2"
pandas = ">=2.2.3, <3"
geopandas = ">=1.0.1, <2"
kubernetes = ">=32.0.1, <33"
nbdev = ">=2.3.34, <3"
papermill = ">=2.6.0, <3"
fastapi = ">=0.115.8, <0.116"
configurable-http-proxy = ">=0.3.0, <0.4"
xformers = "==0.0.29"
triton = ">=3.1.0, <4"
cut-cross-entropy = ">=25.1.1, <26"
unsloth-zoo = ">=2025.2.5, <2026"
protobuf = ">=3.20.3, <4"
datasets = ">=3.3.1, <4"
hf-transfer = ">=0.1.9, <0.2"
tqdm = ">=4.67.1, <5"
ipywidgets = ">=8.1.5, <9"
trl = ">=0.15.1, <0.16"
pip = ">=25.0.1, <26"
openai = ">=1.63.2, <2"
langchain-openai = ">=0.3.6, <0.4"
langchain-aws = ">=0.2.13, <0.3"
langchain-anthropic = ">=0.3.7, <0.4"
langchain-cohere = ">=0.4.2, <0.5"
langchain-google-genai = ">=2.0.9, <3"
langchain-mistralai = ">=0.2.6, <0.3"
langchain-nvidia-ai-endpoints = ">=0.3.9, <0.4"
folium = ">=0.19.4, <0.20"
matplotlib = ">=3.10.0, <4"
mapclassify = ">=2.8.1, <3"
together = ">=1.3.14, <2"
umap-learn = { version = ">=0.5.7, <0.6", extras = ["plot"] }
graphviz = ">=0.20.3, <0.21"
orjson = ">=3.10.15, <4"
dataset = ">=1.6.2, <2"
wandb = ">=0.19.6, <0.20"
python-levenshtein = ">=0.26.1, <0.27"
byaldi = ">=0.0.5, <0.0.6"
pdf2image = ">=1.17.0, <2"
duckduckgo-search = ">=7.4.3, <8"
tiktoken = ">=0.9.0, <0.10"
beautifulsoup4 = ">=4.13.3, <5"
bm25s = ">=0.2.7.post1, <0.3"
ffmpeg-python = ">=0.2.0, <0.3"
pyaudio = ">=0.2.14, <0.3"
pypdf = ">=5.3.0, <6"
cartesia = ">=1.4.0, <2"
bert-score = ">=0.3.13, <0.4"
rouge-score = ">=0.1.2, <0.2"
evaluate = ">=0.4.3, <0.5"
seaborn = ">=0.13.2, <0.14"
osmium = ">=4.0.2, <5"
osmnx = ">=2.0.1, <3"
rasterio = ">=1.4.3, <2"
gdal = "==3.10.1"
h3 = ">=4.2.1, <5"
ipyleaflet = ">=0.19.2, <0.20"
pyrosm = ">=0.6.2, <0.7"
pydriosm = ">=2.2.0, <3"
r5py = { git = "git+https://github.com/r5py/r5py.git" }
routingpy = ">=1.3.0, <2"
polyline = ">=2.0.2, <3"
